#!/bin/bash
# ==============================================================================
# MasterDnsVPN Production Installation & Configuration Script
# Complementary layer (wrapper/supplement) to an official/original proxy script
# Target: Raw Ubuntu 22.04 LTS
# ==============================================================================

# Ensure script is run with root privileges
if [ "$EUID" -ne 0 ]; then
  echo -e "\e[31m❌ ERROR: Please run this installation script as root (sudo bash install.sh).\e[0m"
  exit 1
fi

echo -e "\e[34m==================================================================\e[0m"
echo -e "\e[36m       MasterDnsVPN Complementary Management Layer Installer      \e[0m"
echo -e "\e[34m==================================================================\e[0m"

# ------------------------------------------------------------------------------
# Phase 1: Clean OS Environment Prep
# ------------------------------------------------------------------------------
echo -e "\n\e[33m[Phase 1/3] Preparing clean OS environment...\e[0m"

echo "1. Performing system update and upgrade..."
apt update -y && apt upgrade -y

echo "2. Disabling firewall (UFW)..."
ufw disable || true

echo "3. Freeing Port 53 (disabling systemd-resolved)..."
systemctl disable --now systemd-resolved || true
rm -f /etc/resolv.conf
echo "nameserver 8.8.8.8" > /etc/resolv.conf

echo "4. Installing system dependencies..."
apt install -y git python3-pip curl sqlite3 lsof

echo -e "\e[32m✓ OS environment prepped successfully.\e[0m"

# ------------------------------------------------------------------------------
# Phase 2: Dual-Script Workflow Integration
# ------------------------------------------------------------------------------
echo -e "\n\e[33m[Phase 2/3] Dual-Script Workflow Integration...\e[0m"

echo -e "\e[1;36m=================================================================="
echo -e "👉 ATTENTION: RUN ORIGINAL SCRIPT FIRST!"
echo -e "=================================================================="
echo -e "Before proceeding, please make sure you have run the official/original"
echo -e "creator's proxy script to configure your NS domain, Port, and generate"
echo -e "the authentic keys (Private Key, Public Key, ShortID, UUID, etc.)."
echo -e "==================================================================\e[0m"
echo -e ""
read -p "Press [ENTER] once you have successfully completed the original script setup and have your keys handy..."

echo -e "\n\e[35mPlease enter the configured NS Domain (e.g., net.abrpars.filegear-sg.me):\e[0m"
read -p "> " NS_DOMAIN
while [ -z "$NS_DOMAIN" ]; do
  echo -e "\e[31mNS Domain is required. Please enter a valid domain:\e[0m"
  read -p "> " NS_DOMAIN
done

echo -e "\n\e[35mPlease enter the local backend Port of the proxy core (e.g., 8080):\e[0m"
read -p "> " BACKEND_PORT
if [ -z "$BACKEND_PORT" ]; then
  BACKEND_PORT="8080"
  echo -e "Using default port: 8080"
fi

echo -e "\n\e[35mPlease enter the authentic Keys / UUID generated by the original script:\e[0m"
read -p "> " PROXY_KEYS

# Create app directory if not exists
APP_DIR="/app"
mkdir -p "$APP_DIR"

# Save configuration
cat <<EOF > "$APP_DIR/config.json"
{
  "ns_domain": "$NS_DOMAIN",
  "backend_port": $BACKEND_PORT,
  "proxy_keys": "$PROXY_KEYS"
}
EOF

echo -e "\e[32m✓ Configuration successfully saved to $APP_DIR/config.json\e[0m"

# ------------------------------------------------------------------------------
# Setup Workspaces and files
# ------------------------------------------------------------------------------
echo -e "\n\e[33m[Phase 3/3] Setting up Complementary Management Scripts...\e[0m"

# Copy files from current directory to production app directory if they exist
for FILE in gateway.py dns_core.py manage.py; do
  if [ -f "$FILE" ]; then
    cp "$FILE" "$APP_DIR/"
    echo "Copied $FILE to $APP_DIR/"
  fi
done

cd "$APP_DIR"

# Ensure execution flags are set
chmod +x gateway.py dns_core.py manage.py

# ------------------------------------------------------------------------------
# Initialize database with WAL
# ------------------------------------------------------------------------------
echo -e "\nInitializing database..."
python3 "$APP_DIR/manage.py" init-db || true

# ------------------------------------------------------------------------------
# Setup systemd services
# ------------------------------------------------------------------------------
echo -e "\nConfiguring Systemd services..."

cat <<'EOF' > /etc/systemd/system/gateway.service
[Unit]
Description=MasterDnsVPN Complementary Port 443 TCP Gateway
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/app
ExecStart=/usr/bin/python3 /app/gateway.py
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

cat <<'EOF' > /etc/systemd/system/dnscore.service
[Unit]
Description=MasterDnsVPN Complementary Port 53 UDP DNS Core
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/app
ExecStart=/usr/bin/python3 /app/dns_core.py
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

# Load and start services
echo "Starting services..."
systemctl daemon-reload
systemctl enable gateway.service
systemctl restart gateway.service
systemctl enable dnscore.service
systemctl restart dnscore.service

# Check statuses
sleep 1
if systemctl is-active --quiet gateway.service; then
  echo -e "\e[32m✓ Gateway Service (Port 443) is active and running.\e[0m"
else
  echo -e "\e[31m⚠️ WARNING: Gateway Service failed to start. Run 'journalctl -u gateway' to debug.\e[0m"
fi

if systemctl is-active --quiet dnscore.service; then
  echo -e "\e[32m✓ DNS Core Service (Port 53) is active and running.\e[0m"
else
  echo -e "\e[31m⚠️ WARNING: DNS Core Service failed to start. Run 'journalctl -u dnscore' to debug.\e[0m"
fi

echo -e "\n\e[34m==================================================================\e[0m"
echo -e "\e[32m          🎉 MasterDnsVPN INSTALLATION COMPLETE! 🎉                \e[0m"
echo -e "\e[34m==================================================================\e[0m"
echo -e "Your complementary gateway layer is fully installed and operating."
echo -e "Manage users and bandwidth with ease:"
echo -e "  \e[33mpython3 /app/manage.py add <username> <limit_mb>\e[0m"
echo -e "  \e[33mpython3 /app/manage.py list\e[0m"
echo -e "  \e[33mpython3 /app/manage.py delete <username>\e[0m"
echo -e "\e[34m==================================================================\e[0m\n"
